- name: Webserver deployment
  hosts: WebServer
  tasks:
    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: Start enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: permit traffic http service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true




