- name: Deploy apache webserver
  hosts: WebServer
  vars:
    web_pkg: httpd
    php_pkg: php
    db_pkg: MariaDb
  tasks:
    - name: Install all packages
      ansible.builtin.yum:
        name:
          - "{{web_pkg}}"
          - "{{php_pkg}}"
          - "{{db_pkg}}"
        state: present
