- name: Remove web deployment
  hosts: WebServer
  become: true
  tasks:
    - name: Stop and disable httpd
      ansible.builtin.service:
        name: httpd
        state: stopped
        enabled: no
    - name: disable firewall
      ansible.builtin.firewalld:
        name: http
        state: disabled
        permanent: true
        immediate: true
    - name: Remove httpd
      ansible.builtin.yum:
        name: httpd
        state: absent
    - name: remove index.html file
      ansible.builtin.file:
        path: /var/www/html/inde.html
        state: absent

