- name: Creating users with their password
  hosts: Developer
  vars_files:
    - /home/devops/Ansible-Playbooks/vars/secret.yml
  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.pwd | password_hash('sha512') }}"
      loop: "{{newusers}}"
