- name: Create user and install php package
  hosts: Developer
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: CloudEngineer
        state: present
    - name: Install package
      ansible.builtin.yum:
        name: php
        state: present

- name: Create user and install httpd package
  hosts: WebServer
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: InfraSupport
        state: present
    - name: Install package
      ansible.builtin.yum:
        name: httpd
        state: present

- name: Create user and install MariaDb package
  hosts: TestServer
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: LinuxSysAdmin
        state: present
    - name: Install package
      ansible.builtin.yum:
        name: mariadb
        state: present
     
